### ISSUE TITLE
Carregar ext e blueprints dinamicamente

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/talkshow#5]
No `create_app` os `ext` e os `blueprints` estão carregando declarativamente.
https://github.com/rochacbruno/talkshow/blob/master/talkshow/app.py#L18 

Trocar por um carregamento dinâmico usando `werkzeug.utils.import_string`

ex:

No `settings.toml` ou no `.env` depois de implementar o #1 

```toml
[default]
EXTENSIONS = ["talkshow.ext.cli", "talkshow.ext.admin"]
BLUEPRINTS = ["talkshow.blueprints.webui", "talkshow.blueprints.restapi"]
```

Criar `ext/extensions.py`

```py
from werkzeug.utils import import_string

def configure(app):
    for ext in app.config.get('EXTENSIONS'):
        mod = import_string(ext)
        mod.configure(app)
    
     # fazer o mesmo para os blueprints...

```

No factory `app.py`

```python
from talkshow.ext import configuration, extensions

def create_app():
    app = Flask(__name__)
    configuration.configure(app)  # config loaded here
    extensions.configure(app)
    return app
....
```
